### ISSUE TITLE
Bug: storybook rem단위 설정과 docs의 description 표시 안됨 문제

### ISSUE THREAD

**Issue by bcround** [Devfolio-team/Devfolio-Client#10]
# Issue: 버그 보고

## 📈 버그가 발생하는 페이지(파일)와 문제점
storybook rem단위 설정해야되는 방법과 storybook의 docs의 description이 표시 안되는 문제

### 스크린샷

<img width="637" alt="스크린샷 2021-04-10 오후 9 28 57" src="https://user-images.githubusercontent.com/71061236/114269798-c4ca2300-9a43-11eb-92a4-d36fc3634148.png">

## 버그가 없을때의 동작 설명

storybook의 docs의 description에 component proptypes에 적어준 주석이 들어가야되고, storybook의 rem과 local의 rem 단위가 같아야합니다

**Comment by HaJunRyu** [comment]
https://storybook.js.org/docs/react/configure/story-rendering#adding-to-head
해당 공식문서를 참고하여 해결 부탁드리겠습니다.

**Comment by HaJunRyu** [comment]
storybook스타일 설정 관련 파일을 추가하였습니다 pull 받으셔서 사용하시면 정상적으로 동작하실것 같습니다. 정상적으로 동작한다면 close issue 부탁드리겠습니다.
